replicaCount: 1

image:
  pullPolicy: Always

ingress:
  hosts:
    - host: ordering.dev.freshcart.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ordering-tls-dev
      hosts: [ordering.dev.freshcart.local]

resources:
  requests: { cpu: '50m', memory: '128Mi' }
  limits:   { cpu: '300m', memory: '384Mi' }

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

config:
  ASPNETCORE_ENVIRONMENT: Development

secrets:
  literal:
    ConnectionStrings__orderingdb: 'Server=tcp:freshcart-dev-sql.database.windows.net,1433;Database=FreshCart.Ordering;Authentication=Active Directory Workload Identity;Encrypt=True'

serviceMonitor:
  enabled: true
