replicaCount: 1

image:
  pullPolicy: Always

ingress:
  hosts:
    - host: basket.dev.freshcart.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: basket-tls-dev
      hosts: [basket.dev.freshcart.local]

resources:
  requests: { cpu: '50m', memory: '128Mi' }
  limits:   { cpu: '300m', memory: '384Mi' }

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

config:
  ASPNETCORE_ENVIRONMENT: Development

secrets:
  literal:
    ConnectionStrings__basketdb: 'Host=freshcart-dev-postgres.postgres.database.azure.com;Database=freshcart_basket;Username=freshcart;Ssl Mode=Require'
    ConnectionStrings__cache: 'freshcart-dev-redis.redis.cache.windows.net:6380,ssl=True,abortConnect=False'

serviceMonitor:
  enabled: true
