apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway
  namespace: freshcart
spec:
  podSelector:
    matchLabels: { app.kubernetes.io/name: gateway }
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector: { matchLabels: { name: ingress-nginx } }
        - namespaceSelector: { matchLabels: { name: freshcart } }
          podSelector:       { matchLabels: { app.kubernetes.io/name: gateway } }
      ports:
        - { protocol: TCP, port: 8080 }
  egress:
    - to:
        - ipBlock: { cidr: 10.0.0.0/8 }            # Redis data-protection ring + downstream service mesh
        - ipBlock: { cidr: 168.63.129.16/32 }      # Azure DNS
    - to:
        - namespaceSelector: { matchLabels: { name: kube-system } }
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }
