apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gateway-spc
  namespace: freshcart
spec:
  provider: azure
  parameters:
    usePodIdentity: 'false'
    useVMManagedIdentity: 'false'
    clientID: '00000000-0000-0000-0000-000000000000'
    keyvaultName: 'freshcart-prod-kv'
    cloudName: ''
    tenantId: '00000000-0000-0000-0000-000000000000'
    objects: |
      array:
        - |
          objectName: cache-connection-string
          objectType: secret
        - |
          objectName: jwt-signing-key
          objectType: secret
  secretObjects:
    - secretName: gateway-keyvault
      type: Opaque
      data:
        - { objectName: cache-connection-string, key: ConnectionStrings__cache }
        - { objectName: jwt-signing-key,              key: Jwt__SigningKey }
