apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: basket-spc
  namespace: freshcart
spec:
  provider: azure
  parameters:
    usePodIdentity: 'false'
    useVMManagedIdentity: 'false'
    clientID: '00000000-0000-0000-0000-000000000000'
    keyvaultName: 'freshcart-prod-kv'
    cloudName: ''
    tenantId: '00000000-0000-0000-0000-000000000000'
    objects: |
      array:
        - |
          objectName: basketdb-connection-string
          objectType: secret
        - |
          objectName: cache-connection-string
          objectType: secret
  secretObjects:
    - secretName: basket-keyvault
      type: Opaque
      data:
        - { objectName: basketdb-connection-string, key: ConnectionStrings__basketdb }
        - { objectName: cache-connection-string, key: ConnectionStrings__cache }
