apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: identity
  namespace: freshcart
spec:
  selector:
    matchLabels: { app.kubernetes.io/name: identity }
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
