{{- if not .Values.secrets.externalSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalog.fullname" . }}-secret
  labels: {{- include "catalog.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.literal }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
