replicaCount: 1

image:
  pullPolicy: Always

ingress:
  hosts:
    - host: delivery.dev.freshcart.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: delivery-tls-dev
      hosts: [delivery.dev.freshcart.local]

resources:
  requests: { cpu: '50m', memory: '128Mi' }
  limits:   { cpu: '300m', memory: '384Mi' }

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

config:
  ASPNETCORE_ENVIRONMENT: Development

secrets:
  literal:
    ConnectionStrings__deliverydb: 'mongodb://freshcart-dev-cosmos.mongo.cosmos.azure.com:10255/freshcart_delivery?ssl=true&retrywrites=false'

serviceMonitor:
  enabled: true
