apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory
  namespace: freshcart
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: '8m'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '60'
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts: [inventory.freshcart.local]
      secretName: inventory-tls
  rules:
    - host: inventory.freshcart.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: inventory
                port: { number: 80 }
