apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: inventory-spc
  namespace: freshcart
spec:
  provider: azure
  parameters:
    usePodIdentity: 'false'
    useVMManagedIdentity: 'false'
    clientID: '00000000-0000-0000-0000-000000000000'
    keyvaultName: 'freshcart-prod-kv'
    cloudName: ''
    tenantId: '00000000-0000-0000-0000-000000000000'
    objects: |
      array:
        - |
          objectName: inventorydb-connection-string
          objectType: secret
  secretObjects:
    - secretName: inventory-keyvault
      type: Opaque
      data:
        - { objectName: inventorydb-connection-string, key: ConnectionStrings__inventorydb }
