{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gateway.serviceAccountName" . }}
  labels: {{- include "gateway.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.azureWorkloadIdentityClientId }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.azureWorkloadIdentityClientId | quote }}
  {{- end }}
{{- end }}
